version: '3.9'
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx_config:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt
  frontend:
    image: bidandows/frontend:sha-afd18f5
    expose:
      - 80
  comments:
    image: comments:1
    environment:
      REACT_EVENT_BUS: http://event-bus:4005
    expose:
      - 4001
  event-bus:
    image: event-bus:1
    environment:
      REACT_POSTS_API: http://posts:4000
      REACT_COMMENTS_API: http://comments:4001
      REACT_MODERATION_API: http://moderation:4003
      REACT_QUERY_API: http://query:4002
    expose:
      - 4005
  moderation:
    image: moderation:1
    environment:
      REACT_EVENT_BUS: http://event-bus:4005
    expose:
      - 4003
  posts:
    image: posts:1
    environment:
      REACT_EVENT_BUS: http://event-bus:4005
    expose:
      - 4000
  query:
    image: bidandows/query:sha-14f035f
    environment:
      REACT_EVENT_BUS: http://event-bus:4005
    expose:
      - 4002
volumes:
  nginx_secrets:
