version: '3.9'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx_config:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt


  frontend:
    image: frontend:2
    expose:
    - 80
  comments:
    image: comments:1
    environment:
      REACT_EVENT_BUS: http://event-bus
    expose:
      - 4001


  event-bus:
    image: event-bus:1
    environment:
      REACT_POSTS_API: http://posts
      REACT_COMMENTS_API: http://comments
      REACT_MODERATION_API: http://moderation
      REACT_QUERY_API: http://query
    expose:
      - 4005

  moderation:
    image: moderation:1
    environment:
      REACT_EVENT_BUS: http://event-bus
    expose:
      - 4003

  posts:
    image: posts:1
    environment:
      REACT_EVENT_BUS: http://event-bus
    expose:
      - 4000


  query:
    image: query:1
    environment:
      REACT_EVENT_BUS: http://event-bus
    expose:
      - 4002

volumes:
  nginx_secrets:


