version: '3.9'

volumes:
  nginx_secrets:
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    container_name: nginx
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx_config:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt
  frontend:
    image: bidandows/frontend:sha-2e58a12
    container_name: frontend
    expose:
      - 80
  comments:
    image: bidandows/comments:sha-9f117d7
    container_name: comments
    environment:
      REACT_EVENT_BUS: http://event-bus:4005
    expose:
      - 4001
  event-bus:
    image: bidandows/event-bus:sha-2e58a12
    container_name: event-bus
    environment:
      REACT_POSTS_API: http://posts:4000
      REACT_COMMENTS_API: http://comments:4001
      REACT_MODERATION_API: http://moderation:4003
      REACT_QUERY_API: http://query:4002
    expose:
      - 4005
  moderation:
    image: bidandows/moderation:sha-9f117d7
    container_name: moderation
    environment:
      REACT_EVENT_BUS: http://event-bus:4005
    expose:
      - 4003
  posts:
    image: bidandows/posts:sha-eb05a06
    container_name: posts
    environment:
      REACT_EVENT_BUS: http://event-bus:4005
    expose:
      - 4000
  query:
    image: bidandows/query:sha-9f117d7
    container_name: query
    environment:
      REACT_EVENT_BUS: http://event-bus:4005
    expose:
      - 4002


