---
- name: "AWS - Install docker"
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - git
        - docker
        - python3-pip

    - name: users | adding docker users (for use without sudo)
      user:
        name: ec2-user
        append: yes
        groups: docker


    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Python pip packages are installed
      pip:
        name: "{{ packages }}"
      vars:
        packages:
        - boto
        - boto3
        - docker-compose
        - PyYAML
        - docker

    - name: Clone of a single branch
      ansible.builtin.git:
        repo: https://github.com/bidandows/devops-test.git
        dest: /home/ec2-user/devops-test
        single_branch: yes
        version: main
    
    - name: Change devops folder ownership
      shell: chown -R ec2-user:ec2-user /home/ec2-user/devops-test

    - name: Start the monitoring docker-compose 
      community.docker.docker_compose:
        project_src: /home/ec2-user/devops-test/infrastructure/monitoring/
        state: present

    - name: Start the application docker-compose 
      community.docker.docker_compose:
        project_src: /home/ec2-user/devops-test/deploy/
        state: present
