name: DevOps-test_CI/CD

on: [push, pull_request, workflow_dispatch]



jobs:

  files-changed:
    name: detect what files changed
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3

      - name: check for devops repo file changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            client:
              - 'client/**'
            event-bus:
              - 'event-bus/**'
            comments:
              - 'comments/**'
            moderation:
              - 'moderation/**'
            posts:
              - 'posts/**'
            query:
              - 'query/**'
  
  frontend:
    if: needs.files-changed.steps.filter.outputs.client == 'true'
    needs: files-changed
    name: build and deploy frontend application
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0
      - 
        name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./client/
          push: true
          tags: bidandows/frontend:${{ SHORT_SHA }}


      -
        name: update docker-compose image value
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.services.frontend.image = bidandows/frontend:${{ SHORT_SHA }}' './deploy/docker-compose.yml'

      - 
        name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update frontend image value on docker-compose"
      - 
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - 
        name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/devops-test
            git pull
            cd deploy
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            docker-compose up -d --force-recreate frontend

